var shoppingList = ["Pain", "Jus", "Bananes", "Citron", "Chemises", "Pantalon"];
var montableau = JSON.stringify(shoppingList);
var taille = JSON.stringify(shoppingList.length);
document.getElementById("list").innerHTML = montableau;
document.getElementById("taille").innerHTML = taille;
shoppingList.push('Mangues');
montableau = JSON.stringify(shoppingList);
taille = JSON.stringify(shoppingList.length);
document.getElementById("list1").innerHTML = montableau;
document.getElementById("taille1").innerHTML = taille;
shoppingList.pop();
shoppingList.pop();
montableau = JSON.stringify(shoppingList);
taille = JSON.stringify(shoppingList.length);
document.getElementById("list2").innerHTML = montableau;
document.getElementById("taille2").innerHTML = taille;
shoppingList[2]='RIZ';
montableau = JSON.stringify(shoppingList);
document.getElementById("list3").innerHTML = montableau;
